export const ADD_PRODUCT = 'ADD PRODUCT';
export const DELETE_PRODUCT = 'DELETE PRODUCT';
export const ADD_PRODUCT_COUNT = 'ADD PRODUCT COUNT';
export const REDUCE_PRODUCT_COUNT = 'REDUCE PRODUCT COUNT';
export const ADD_PRICE = 'ADD PRICE';
export const REDUCE_PRICE = 'REDUCE PRICE';
export const RESTART_COUNT = 'RESTART COUNT';